### ISSUE TITLE
Project kick off

### ISSUE THREAD

**Issue by douglasF5** [douglasF5/mini-budget-tracker-web-app#1]
## Tasks
- [x] create the project private repo on GitHub
- [x] create a project board for the repo
- [x] start the backlog
- [x] gather code repos from other devs that worked on this project
